<table>
    <tr>
        <th>
            <?= __("Id")?>
        </th>
        <th>
            <?= __("Title")?>
        </th>
        <th>
            <?= __("Content")?>
        </th>
    </tr>
    <?php
    $blogs = $block->getBlogs();

    foreach ($blogs as $blog) {?>
        <tr class="blog-list-table-row">
            <td class="blog-list-table-id">
                <?= $blog->getId()?>
            </td>
            <td class="blog-list-table-title">
                <?= $blog->getTitle()?>
            </td>
            <td class="blog-list-table-content">
                <?= substr($blog->getContent(), 0, 20).'...'?>
            </td>
            <td class="blog-list-table-action blog-list-table-action-edit">
                <a href="<?= $block->getUrl('blog/manage/edit', ['id'=>$blog->getId()])?>">
                    <?= __('Edit') ?>
                </a>
            </td>
            <td class="blog-list-table-action blog-list-table-action-delete">
                <a href="<?= $block->getUrl('blog/manage/delete', ['id'=>$blog->getId()])?>">
                    <?= __('Delete') ?>
                </a>
            </td>
        </tr>
        <?php } ?>
    </table>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "bloglist": ""
        }
    }
</script>